[default]
src = 'src'
out = 'out'
libs = ['lib']

remappings = ['@openzeppelin/=lib/openzeppelin-contracts-upgradeable']

# See more config options https://github.com/gakonst/foundry/tree/master/config