[default]
src = "src"
out = "out"
test = "test/sol"
libs = ["lib"]

solc_version = "0.8.10"
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/gakonst/foundry/tree/master/config