[default]
src = "src"
out = "artifacts/foundry/out"
test = "test/sol"

solc_version = "0.8.10"
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/gakonst/foundry/tree/master/config