[default]
src = "src"
out = "artifacts"
test = "test/sol"

remappings = [
    "@chainlink/=node_modules/@chainlink/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@uniswap/=node_modules/@uniswap/",
]

solc_version = "0.8.10"
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/gakonst/foundry/tree/master/config